### ISSUE TITLE
figure out how profile & group images will work

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#117]

**Comment by sebgrebe** [comment]
As part of this, we should try to add the random profile pic feature @Richenda [asked for](https://github.com/rtcharity/hubreboot/issues/97#issuecomment-453927284)

**Comment by Manoj-nathwani** [comment]
This is a pretty big task. We need to do the following:
- Figure out how we can store images as blobs on azure
- Link up the django site so users can upload images through `/profile/edit` and they're saved to blob storage. We then save a URL to the file in our database
- Migrate old profile pictures. This is pretty straight forward because I have a local version of the site I scraped, so i'll just need to write a script to fetch all URLs there. Then we can download them & upload them to our new blob storage solution.

- also yes, if a user doesn't upload their own image, we can randomly give them one of 5 examples we have and let them chose between that too.
