### ISSUE TITLE
Menu: Burger, not list

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#142]
>We consciously decided against this as it is unusual to have a hamburger menu on a desktop page. The hamburger menu still exists on mobile. Let us know if you feel strongly about this.
@sebgrebe sorry whose we? As PM I need to be included in any decisions about design. If it's about tech architecture that's different.

So maybe I am using the description wrong here? I'll just spell out what I mean as plainly as I can to make sure :) On all versions of the Hub, no matter what device, the menu needs to be compacted into a single icon on the top right that is three horizontal lines. Clicking on that line should result in a drop down menu. Can you confirm that we're talking about the same thing?

It is interesting that this style supposed to be unusual on a desktop website. I have to say I've not noticed that. I have used many websites on my laptop that present their menus in this way too. It looks much cleaner and more minimalist. What we have now is cluttered, it takes away from the other objects on the page. Also it is redundant. The home page already has big obvious feature icons for important features. So there is no need at all to _additionally_ have a row of options in the header. At most we can have the log in icon in addition to the menu icon. 

If there isn't any technical barrier then yes please, I am very certain about this design choice.

_Originally posted by @Richenda in https://github.com/rtcharity/hubreboot/issues/137#issuecomment-457966765_

**Comment by sebgrebe** [comment]
@richenda I know the way the menu unfolds isn't perfect - having it overlap the faces only partially, as we used to have it, is quite tricky though if we want to keep the look consistent across browsers. 

Let me know what you think.

**Comment by Manoj-nathwani** [comment]
| ![image](https://user-images.githubusercontent.com/2634482/51868045-f06e0080-2344-11e9-8dff-7ae6b9609ce3.png)| ![image](https://user-images.githubusercontent.com/2634482/51867985-cc122400-2344-11e9-9765-9eb13fb97375.png) |
|---|---|

## Can I request:
- Add login/signup back as regular navigation buttons so it's not hidden
- Before opening the menu the boarder is black which is a little ugly. Maybe white or grey?
- When open, make the purple slightly less transparent. It's a little confusing
- Push the purple box slightly more left so it's aligned with the button and maybe give it a `border-radius`
- We could also remove icons for the sake of making the box less wide 🤔 Just thinking out loud because that bottom one is much wider than other options

**Comment by Richenda** [comment]
Thanks @sebgrebe I love it.
Responding to @Manoj-nathwani I think having login/register as a regular icon next to the menu icon is fine. As long as the rest are tucked away like now.

I like the transparent purple but we could also try solid pale grey with purple font if that helps? I think the icons in the menu are useful but I have no strong views about removing them.

I don’t think the menu should have a border but I’m not sure what Manoj means by radius.

**Comment by Richenda** [comment]
But yeh the menu icon must have no border

**Comment by sebgrebe** [comment]
@Richenda @Manoj-nathwani Thanks for the input! This should all be done now.

**Comment by Manoj-nathwani** [comment]
Awesome! This is great

![image](https://user-images.githubusercontent.com/2634482/51912123-6f0d8100-23cb-11e9-9917-a33a9d7600aa.png)
before | after

Can we slightly change it to something closer to this?
Though I feel like i'm nitpicking now 😅 

It's just less opacity, no top-right border-radius and the login/signup buttons closer together
Defiantly feel like nitpicking though sorry 🙈

**Comment by Richenda** [comment]
Oh and it's looking really good generally so thanks for the effort and help.

**Comment by sebgrebe** [comment]
@Richenda @Manoj-nathwani Done. I'm closing this now before you get more ideas 😄

**Comment by Manoj-nathwani** [comment]
- Just removed the little curved corners at the top
- Totally my own OCD kicking here though, so I just did it

![image](https://user-images.githubusercontent.com/2634482/51991787-bff0a880-24a3-11e9-83cd-7c092ce28890.png)


![image](https://user-images.githubusercontent.com/2634482/51991698-8d46b000-24a3-11e9-97f5-57940a1272f3.png)

**Comment by Richenda** [comment]
I like your OCD instincts @Manoj-nathwani thanks for that. Curved corners are a nice look but don't fit with the style strategy for the Hub which goes for sharp/clean cut corners everywhere.

@sebgrebe is it easy to make the colour more pale grey or more translucent when you hover on the menu button? Rather than black/dark grey

**Comment by sebgrebe** [comment]
> @sebgrebe is it easy to make the colour more pale grey or more translucent when you hover on the ? > menu button? Rather than black/dark grey

Done.

**Comment by Richenda** [comment]
Thank you. I love it!
