### ISSUE TITLE
Only show "other" fields when appropriate 

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/hubreboot#209]
# Problem
![image](https://user-images.githubusercontent.com/2634482/52329508-8da3f580-2a25-11e9-913c-7a36ce5dcf82.png)

# Solution
- Add a little bit of javascript so the free-text field is only displayed when the above dropdown is set to `Other`. This problem appears on multiple forms, so add the logic to the `form.html` file and use some kinda class to apply it to all relevant fields automatically

**Comment by sebgrebe** [comment]
@Manoj-nathwani Done. Move to done if you're happy.

**Comment by Manoj-nathwani** [comment]
![image](https://user-images.githubusercontent.com/2634482/52607601-69bf3480-2ea9-11e9-858f-1f232c0094c8.png)

By default my `other` field still shows up :/

**Comment by sebgrebe** [comment]
![screen shot 2019-02-12 at 07 56 00](https://user-images.githubusercontent.com/15908208/52620163-b00d9700-2e9b-11e9-81e7-a928a5856e97.png)
Hm, I can't reproduce this error on my profile. 

The reason might be that on your profile, you have an "other" cause area (global warming). I've set it up such that if you selected an "other" previously, you can also see the other box immediately when you come to the edit page - if you haven't selected on, you don't. It's really the only possibility because alternatively you have to unselect and then again select the other box to the the other field.

**Comment by Manoj-nathwani** [comment]
yeah fair enough. It's a small edge case anyway 👍
