### ISSUE TITLE
Migrate the group data from the Airtable

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#253]

**Comment by taymonbeal** [comment]
Have got a script that downloads the data from the Airtable. Now just figuring out what form to get it into for Django.

**Comment by taymonbeal** [comment]
Okay, the Airtable migration works with the following caveats (in descending order of severity):
- Geocoding doesn't work yet because our existing solution isn't allowed to be used in bulk. We have to figure out something else.
- Things that are "presences" rather than "groups" are currently included. Is that desired? It's an easy fix.
- Only the data from the "Active" sheet is included. Do we care about the others?
- No information about organizers was imported. I'm in favor of waiting until post-launch for this; we can easily manage data updates ourselves in the interim.

**Comment by taymonbeal** [comment]
Also, should we display the organizer's personal email if it's the only one we've got?
