### ISSUE TITLE
Potential usability shortcomings in "Key Facts"

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/hubreboot#289]
![image](https://user-images.githubusercontent.com/14195560/53124153-872a7900-350f-11e9-9101-ca6af30c269a.png)

**Comment by taymonbeal** [comment]
Do the editing forms not work or is this just a complaint about things being confusing?

**Comment by michaltrzesimiech** [comment]
Just a complaint

**Comment by taymonbeal** [comment]
Remove the "fix before launch" label after either applying a temporary fix or deciding that we're not going to do that now.

**Comment by michaltrzesimiech** [comment]
We will remove the duplicated information for now, then remove the label.

**Comment by sebgrebe** [comment]
so just remove all the key facts that show up on the other cards? Happy to do that

**Comment by Richenda** [comment]
Just going to repeat myself here: "Richenda Herzig [10 minutes ago]
Not wishing to muddy the water here… this issue of duplicates is complicated. Basically the way this has happened was (1) I design profiles and in my design settings are all on a page somewhere else and the Key Facts box is the only thing displaying info about users. (2) Manoj introduces those little sections at the bottom of profiles for technical reasons… which I forget. In doing so we now end up with both a key facts box AND editable sections which repeat some of those facts. I never really updated on the Key Facts section (my bad). 

Now that we have both, we could ask… do we need the Key Facts box at all? Is it still useful? My intuition is that it will be faster for people to find what they know about people when visiting a page through the Key Facts box, and looking down to the editable sections will slow people down because of the images and boxes and things. Perhaps this doesn’t matter if we are providing sophisticated filters and search features that let a person find, e.g., all users available to volunteer, or all users interested in Existential Risk and so on." 

The point is that there might be a purpose or point in the duplication. But I guess we can reverse any change now at a later stage?

**Comment by michaltrzesimiech** [comment]
@sebgrebe  Let's remove any duplicated information from Key Facts for now and revise optimal solution post-launch.

**Comment by Richenda** [comment]
Once this is implemented, please keep this issue open and relabel and retag. Or make a new one.
