### ISSUE TITLE
Feedback: Home page

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/hubreboot#55]
First version of the home page: https://eahub.azurewebsites.net/

Currently with dummy icons.

Please leave feedback in the comments, I'll try to implement them

**Comment by Richenda** [comment]
Looks good. This is what I see in Chrome on MacOS 10.14.2 I would suggest just adding a little more space between the logo and drop down menu and the image. It's a bit squashed right now. The drop down menu will need to be opaque I think. I would suggest making it either very very light grey with black text or the lighter purple from the set site colour pallette. Icons plus text are fine for size but obviously will need to be arranged more symmetrically.  Thanks!

<img width="1439" alt="screenshot 2019-01-02 at 15 33 40" src="https://user-images.githubusercontent.com/14843012/50617827-f686d380-0ea3-11e9-809b-983b6c4e5e4c.png">

**Comment by Richenda** [comment]
The caption is currently grammatically incorrect. It should be 'Join over 1700' rather than 'Join the over'. But actually I think that what would be more conventional and appropriate for a site like this is to say 'Join 1700 + EAs from around the world'. The plus icon makes 'over' unnecessary.

**Comment by Richenda** [comment]
Is that figure accurate Manoj?

**Comment by Richenda** [comment]
Here are the feature icons and hover text: https://github.com/rtcharity/hubreboot/issues/45

**Comment by Richenda** [comment]
@sebgrebe Ignore the fact that this is a Wordpress theme. Do you see how if you scroll, it makes you move all the way to the next block of colour. You can't stop halfway? https://alvarotrigo.com/fullPage/#page1 This is the kind of effect I want for the home page. I want people to scroll down to the map, but when they start the scroll it makes them go all the way until the map is in focus. The map should be under the feature icons.

**Comment by sebgrebe** [comment]
@Richenda This shouldn't be too hard to do. 

Independent of this: Does this mean there won't be an individual page for the map, but the map will live on the home page? Or do you want an extra page for the map nonetheless? (Remember that we're linking to the map from the little maps on /profile/ID and /group/ID)

**Comment by Richenda** [comment]
> @Richenda This shouldn't be too hard to do.
> 
> Independent of this: Does this mean there won't be an individual page for the map, but the map will live on the home page? Or do you want an extra page for the map nonetheless? (Remember that we're linking to the map from the little maps on /profile/ID and /group/ID)

@sebgrebe so remember we talked about this a few weeks ago and I think it was you saying that it didn't make sense to have the map as it's own page that people have to navigate to and that you thought it would be better for it to be on the home page like with the original Hub. And then we were talking about whether it would look too messy or not and I said I would go away and think about it.

So I thought about it and decided that I didn't want it to be directly under the home page banner as I think it looks too messy. But I think it can go under the feature icons without clashing, and it can even be a positive thing down there because older users are used to seeing it on the home page, and it is a very popular feature... and these days modern websites often do have long home pages with different things to scroll through. So I think it's positive on the front page. As for the map previews we have on group and personal profiles, and on the group feature page... I think that if we can't redirect people to a particular segment of the home page then we can also have it as it's own feature page. I don't think there's any harm in their being many roads to Rome. What do you think?

**Comment by sebgrebe** [comment]
@Richenda Implemented this now ([pull request](#95)].  
The only thing I haven't done yet is the scroll effect because this doesn't seem essential to get the page ready for a beta-release. Will do this at a later stage
